---
apiVersion: v1
kind: Pod
metadata:
  name: chat
  namespace: manifest-playground
spec:
  containers:
  - name: chat
    image: kevbac/feathers-chat
    imagePullPolicy: IfNotPresent
    command:
     - bash
     - -c
     - "npm start"
    ports:
    - containerPort: 8080
      protocol: TCP
  restartPolicy: Always
